### ISSUE TITLE
Upload photo not working

### ISSUE THREAD

**Issue by kuzubov** [LevPasha/Instagram-API-python#142] opened 2017-04-18 05:40 UTC
Total Photo in this folder:18
Request return 429 error!
Login success!

Progress :[1] of 18
Now Uploading this photo to instagram: 01.jpg
Request return 400 error!
Sleep upload for seconds: 1018

**Comment by ThomasMW** [comment] 2017-04-18 16:12
A 400 status code means request is not accepted. You probably need to reverify the account.

Log in using a browser and follow the instructions.

**Comment by snenkov** [comment] 2017-04-22 23:17
I have the same 200 status code error. I logged through my account from the browser and my phone and everything works fine. 
During one of my runs, it just stopped working, so I am very unsure why... Does anyone know a fix for this?

**Comment by ThomasMW** [comment] 2017-04-24 11:27
If it works with another account it means the problem is account related. It can mean one account is restricted from using the API end-points.

To test this you could run the same code on multiple accounts to see if the results are different.

If needed use different IP addresses to find out an IP is flagged.

**Comment by snenkov** [comment] 2017-04-24 12:37
Hi Thomas,
Thnaks for the tip, I will definitely try this. Do you know what may the rwason be, as I don't want it to happen woth another account?
Have you (or others) downloaded bulk data from Instagram on a daily basis and not get restricted to use the endpoints?
My goal is to find a sustainable usage with low or no risk of being restricted.

**Comment by ThomasMW** [comment] 2017-04-24 12:48
I can't really say right now for as I don't how you used the API.

One important thing is to always stick to the Instagram rate limits for liking, commenting, and following/in following. A simple Google search will get you the current limits.

Downloading or uploading a lot of photo's shouldn't be a problem as long as you make sure you aren't sending too many requests in a short period of time. Make sure you build in small pauses between requests.

Account age also matters a lot, older accounts who are verified and have more real followers and followings can get away with more than brand new accounts.

**Comment by snenkov** [comment] 2017-04-24 13:38
That's very useful info: the only thing I do is to download data for mine and otger accounts (such as likes per photo etc.) I do not do any liking , following, unfollowing etc. Also, my instagram (as a regular user) works perfectly, I only get error 400 when using the api through python now. (So it gets me nothing with my account).
I will check if there are rate limits liked to the downloading of data... thanks!

**Closed** 2018-01-12 19:56 UTC
